import '../styles/globals.css';

import type { AppProps } from 'next/app';
import Head from 'next/head';
import React from 'react';

import Web3ContextProvider from '../contexts/web3Context';

const DefaultLayout = ({ children }) => children;

function MyApp({ Component, pageProps }: AppProps) {
  const Layout = (Component as any).Layout || DefaultLayout;

  return (
    <>
      <Head>
        <title>BlitPop</title>
        <meta httpEquiv="content-language" content="en" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:ital,wght@0,400;0,800;1,500;1,700&display=swap"
          rel="stylesheet"
        />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Bangers&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Bangers&family=Montserrat&display=swap"
          rel="stylesheet"
        />

        <title>BlitPop</title>
        <meta name="title" content="BlitPop" />
        <meta
          name="description"
          content="Onchain Blitmap derivatives in a pop art style"
        />

        <meta property="og:type" content="website" />
        <meta property="og:url" content="https://blitpop.0xessential.com/" />
        <meta property="og:title" content="BlitPop" />
        <meta
          property="og:description"
          content="Onchain Blitmap derivatives in a pop art style"
        />
        <meta
          property="og:image"
          content="https://blitpop.0xessential.com/burger.png"
        />

        <meta property="twitter:card" content="summary_large_image" />
        <meta
          property="twitter:url"
          content="https://blitpop.0xessential.com/"
        />
        <meta property="twitter:title" content="BlitPop" />
        <meta
          property="twitter:description"
          content="Onchain Blitmap derivatives in a pop art style"
        />
        <meta
          property="twitter:image"
          content="https://blitpop.0xessential.com/burger.png"
        ></meta>
      </Head>
      <Web3ContextProvider>
        <Layout>
          <Component {...pageProps} />
        </Layout>
      </Web3ContextProvider>
    </>
  );
}
export default MyApp;
